name: CI/CD Pipeline

# Auslöser der Pipeline: Push auf main-Branch oder Pull Requests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout-Code aus dem Repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setze Node.js-Umgebung auf
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 3. Installiere die Abhängigkeiten
      - name: Install dependencies
        run: npm install

      # 4. Baue das Projekt
      - name: Build project
        run: npm run build

      # 5. Führe Tests aus
      - name: Run tests
        run: npm test
