name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Code-Checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 3. Abh채ngigkeiten installieren
      - name: Install dependencies
        run: npm install

      # 4. Code builden
      - name: Build project
        run: npm run build

      # 5. Tests ausf체hren
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Deploy Step (hier wird z. B. ein Deployment auf einen Server oder in die Cloud durchgef체hrt)
      - name: Deploy to production
        env:
          NODE_ENV: production
        run: |
          echo "Starting deployment..."
          # Beispiel f체r ein Deployment (ersetze diesen Teil durch dein eigenes Deployment-Skript)
          # z.B. Heroku, AWS, oder eigener Server
